# Generated by Django 2.2.6 on 2019-10-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20191015_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='avatar',
            field=models.FileField(blank=True, default='rooms/avatar-chat.svg', null=True, upload_to='rooms'),
        ),
    ]
