# Generated by Django 2.2.6 on 2019-10-17 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20191016_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='room',
            name='created_by',
        ),
    ]
