# Generated by Django 2.2 on 2019-10-11 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191010_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='followed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='account.Profile'),
        ),
    ]
